var name = 'kim'; // let, var, const 사용 가능
var age = 50;
var TF = true;
var none = null;
var un = undefined;
var array = ['Teemo', 'chan'];
var obj2 = { member: 'Teemo', member2: "hello" };
var primitive = 'hello'; // 자동으로 문자열로 해줌
var arr3 = [2, 3, 4, 5, 6, 7, 8, 'sdfjslf'];
var pobj = { Teemo: 'cute' };
